src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfigurationLoader.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfigurationLoaderTest.java

SonarQube returns an empty branch list if the project doesn't already exist, which results in an error being thrown telling the user to re-run the scan with no branch parameters set, even if no branch analysis parameters were specified. However, when a project is created through the Web interface, SonarQube automatically creates a default branch named `master` which the scanner picks up as the primary branch and targets if no other parameters are specified. This inconsistency means users can't have SonarQube automatically create projects, but have to use the Web interface to set-up any projects first.
To make the setup consistent, the check for no branches existing is extended to also check if any of the branch parameters have also been specified. This way, if no branches exist but no …

#1: Only error when no branches exist and non-master branch specified

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityBranchLoaderDelegate.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityBranchLoaderDelegateTest.java

A lookup is performed on the target branch of a pull request to ensure the branch exists, since SonarQube uses the target branch as the base for comparing metrics on the Pull Request. However, the retrieved branch is then used incorrectly, with the UUID of the retrieved branch's target branch being returned as the target for the Pull Request, rather than the UUID of the retrieved branch. As long-lived branches that are generally targeted by Pull Requests will not have a target branch, this may result in a `NoSuchElementException` from SonarQube's Compute Engine when trying to use the non-existent UUID, or could result in SonarQube showing the wrong branch as being targeted for a pull request thereby picking up new issues on the source branch incorrectly where a short-lived branch is …

#4: Use correct target branch when generating a pull request's details

---

src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityProjectPullRequestsLoader.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityProjectPullRequestsLoaderTest.java

When running a scan, the scanner engine loads existing Pull Request details from SonarQube core using a Web Service, but fails to deserialise the response due to a mismatch between the data types in the returned data structure and the target model.
Changing the deserialisation method to parse the impacted date field to a Date object using a Date Formatter, and then convert the parsed date to the target model's `long` type resolves this issue.

#6: Fix error when loading project's existing Pull Requests

---

README.md
build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityBranch.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityBranchLoaderDelegate.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfiguration.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityBranchLoaderDelegateTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityBranchTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfigurationLoaderTest.java

SonarQube 7.8 contains changes to the APIs required for managing branches, with new methods having been introduced, and the existing `getMergeBranchUUid` method signature in `org.sonar.ce.tasj.projectanalysis.Branch` modified in a non-backwards-compatible way. Due to the incompatible changes, the supported SonarQube API version has been bumped from 7.4 to 7.8 and any methods that only existed to support older SonarQube versions have been removed.
The 7.8 release of SonarQube does not currently have a sonar-plugin-api dependency released with it, so the SonarQube 7.7 dependency for the plugin-api component is being used in its place.

#19: Add support for SonarQube 7.8 APIs

---

src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPlugin.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityBranchEditionProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfigurationLoader.java
src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPluginTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityBranchEditionProviderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfigurationLoaderTest.java

SonarQube 7.9 contains an signature change on the method in `BranchConfigurationLoader` interface, and additional checks on the current edition of SonarQube to restrict what plugins/versions can support Branch Analysis.
An additional method implementation has therefore been added to deal with the interface change, whilst retaining the old method for backwards compatibility, and a new `CommunityBranchEditionProvider` has been added to make SonarQube Compute Engine believe that Developer Edition is currently being executed thereby allowing the branch restriction checks to be satisfied.

Add support for SonarQube 7.9

---

.travis.yml
README.md
build.gradle
src/test/java/com/github/mc1arke/sonarqube/plugin/classloader/ClassReferenceElevatedClassLoaderFactoryTest.java

Adds integration with Travis for a CI build for Java 8 and Java 11, and fixes the tests that this integration highlighted were failing on Java 11.

Enable CI Build and fix tests on Java 9 and above

---

src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityProjectPullRequestsLoader.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityProjectPullRequestsLoaderTest.java

Fix NPE when branch is orphaned

---

README.md
src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPlugin.java
src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPluginBootstrap.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityBranch.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchParamsValidator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityProjectBranchesLoader.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityProjectPullRequestsLoader.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/ScannerWsClientWrapper.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/CommunityComponentKey.java
src/main/resources/META-INF/services/org.sonar.core.extension.CoreExtension
src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPluginBootstrapTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPluginTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchParamsValidatorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityProjectBranchesLoaderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityProjectPullRequestsLoaderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/ScannerWsClientWrapperTest.java

Replaces references to the removed `ScannerUtils` class with Java's `URLEncoder`, and adds implementations of new methods introduced into SonarQube 8.0's interfaces. Since SonarQube 8.0 also changed `ScannerWsClient` from a class to an interface, the `ScannerWsClient` is now invoked through reflection in `ScannerWsClientWrapper` to prevent a `java.lang.IncompatibleClassChangeError` being thrown during invocation.
On top of this, SonarQube Compute Engine now contains a Java Security Manager that blocks access to retrieving `ClassLoader`s, so prevents the work-around used to access the branch API classes required for this plugin to execute. Moving the loading of the impacted classes into a `CoreExtension` and bypassing the class-loading manipulation for these classes overcomes this problem. …

#38: Add support for SonarQube 8.0

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/response/Discussion.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/response/Note.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/response/User.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfigurationLoader.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/ScannerPullRequestPropertySensor.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfigurationLoaderTest.java

* Support automatic configuration in GitLab CI
* Align property names with sonar developer edition
* Autodelete comments
* Don't fail if no new coverage condition is provided
* Support multiple pipelines on one commit
Fixes #84
Fixes #85
Fixes #86
Closes #74

Gitlab PR Decorator Fixes for Sonar 8.1

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecoratorTest.java

Hi, 
thanks for this great plugin. I did some tests decorating merge request with our gitlab server and had to change this to make it work.
1. always get the commits regardless of deleteCommentsEnabled (otherwise no discussion is created below)
2. add old_path when adding the discussion (otherwise the comment is not displayed inline in the diff in gitlab)
Kind regards,
Uwe

Fix adding discussions for gitlab

---

.gitignore
src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPlugin.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PullRequestBuildStatusDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PullRequestPostAnalysisTask.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/UnifyConfiguration.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/server/BitbucketServerPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/CheckRunProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/GithubPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/ScannerConfigurationLoaderSensor.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PullRequestPostAnalysisTaskTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/UnifyConfigurationTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/server/BitbucketServerPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/GithubPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProviderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/ScannerConfigurationLoaderSensorTest.java

During the merging of the configurations for PullRequestBuildStatusDecorator, I removed the explicit reading of the default parameter values from PropertyDefinitions for github decorator. According to the implementation of org.sonar.api.config.Configuration sonar reads them itself. Unfortunately, I have an opportunity to check only with BitbucketServer and it really works with this command
```
docker run -ti -v $(pwd):/usr/src newtmitch/sonar-scanner:4.0.0-alpine \
-Dsonar.host.url=$SONAR_URL \
-Dsonar.projectKey="project:repo" \
-Dsonar.projectName="repo" \
-Dsonar.projectBaseDir=/usr/src \
-Dsonar.sources=. \
-Dsonar.pullrequest.key="13" \
-Dsonar.pullrequest.branch="test-sonar" \
-Dsonar.pullrequest.base="master" \
-Dsonar.pullrequest.provider="BitbucketServer" \ …
```

#72: Allow override configuration from CLI

---

build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityReportAnalysisComponentProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v3/DefaultLinkHeaderReader.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v3/LinkHeaderReader.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v3/RestApplicationAuthenticationProvider.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v3/DefaultLinkHeaderReaderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v3/RestApplicationAuthenticationProviderTest.java

When trying to find authentication tokens for accessing a repository, the list of repositories attached to a token are currently iterated over until one is found with a matching name, or the end of the retrieved list is reached. However, this search is not taking into account pagination in the response from Github, so any list of repositories that is greater than the default page size fails to find a matching authentication token if the repository is not present on the first page of the repository list. To resolve this, the response is checked for a `Link` header with a `rel="next"` element, with the link in this header being followed for each response until a matching repository is found, or the header is not present.

#103: Handle pagination on repositories response

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/UpdateCheckRun.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProviderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/UpdateCheckRunTest.java

Creating a check run on Github limits the number of annotations in the initial report to a maximum of 50, otherwise the request is silently ignored with no error returned in the response. To overcome this, the initial report is limited to 50 annotations, with any remaining annotations submitted in groups of 50 in subsequent update calls.

#154: Submit annotations in batches of 50 to Github

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java

Tested this on local (docker/kubernetes) setup. With this diff gitlab MR decoration began to work as it now honors the system properties for proxy. (http.proxyHost, http.proxyport, etc.)
Came up initially when setting it up with sonar 8.2. See [here](https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/112#issuecomment-614627627).

[GITLAB] Support proxy by using HttpClients.createSystem()

---

README.md
src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPlugin.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PullRequestPostAnalysisTask.java
src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPluginTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetailsTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PullRequestPostAnalysisTaskTest.java

Add images base URL property

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecoratorTest.java

When in Sonar conditions there is no new_coverage condition (and I doubt that this condition is necessary) the plugin throws Exception. IllegalStateException("Could not find New Coverage Condition in analysis")

Removed exception "IllegalStateException" if could not find New Coverage Condition in analysis and replaced to "0"

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/UpdateCheckRun.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/CreateCheckRunTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProviderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/UpdateCheckRunTest.java

The previous fix for any pull request that had more than 50 issues had allowed an initial check run to be created, and then submitted the next batch of 50 issues to Github but failed to parse the response properly, so threw an error at that point, subsequently only submitting 100 issues to Github for each scan before causing the Compute Engine task to fail. The correct type is now being specified for the parse of Github's response, and unnecessary fields in the expected response object have been removed to allow the response to be parsed properly.

#154: Correctly report more than 50 issues to Github

---

.github/workflows/build.yml

Github does not expose secrets during the execution of actions on pull requests from forked projects, so the Sonar task would always fail on external pull requests. Additionally, anyone forking the project would have had the Sonarqube step fail unless they'd specifically setup Sonarqube secrets on their fork. To overcome this, the `sonar` step is now executed based on the condition of the `SONAR_TOKEN` secret being present in the current execution environment.
Includes a fix for incorrect syntax and variable references in the Pull Request Sonar analysis block.

Fix execution of Sonarqube on forked repositories and pull requests

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProvider.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProviderTest.java

Fix proposal for https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/190
Only decorate with unresolved and non closed issues on Github pull requests.
Currently, fixed issues are still displayed on line 0 of the file, although it is correctly marked as fixed in Sonarqube

Fix #190 - Don't decorate with fixed issue

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketServerPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketClient.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecoratorTest.java

Below are couple of fixes of BitBucket decoration in sq-8_2-support branch
- replace `.getAlmRepo()` and `getAlmSlug()` calls (to get correct parameters order in `insights/1.0/projects/%s/repos/%s/` templates)
- fix `almSettingDto.getUrl()` call (missed method)
- add debug logging (well, for debug)

BitBucket decoration fix

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProvider.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProviderTest.java

Fix proposal for https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/189
On Github PR decoration, annotation for single line issues are reported on the wrong line, because end line of the annotated error is incremented by one.

Fix #189 - Annotation on wrong line

---

README.md
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityReportAnalysisComponentProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketClientFactory.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketCloudClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketCloudException.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketException.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketServerClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/BitbucketConfiguration.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/CodeInsightsAnnotation.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/CodeInsightsReport.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/DataValue.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/ReportData.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/cloud/CloudAnnotation.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/cloud/CloudCreateReportRequest.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/server/Annotation.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/server/CreateAnnotationsRequest.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/server/CreateReportRequest.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/server/ErrorResponse.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/server/ServerProperties.java
src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPluginBootstrapTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPluginTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketClientFactoryUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketCloudClientUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketServerClientUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/BitbucketConfigurationUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/CommunityBranchSupportDelegateTest.java
src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

This commit provides support for the newly created bitbucket cloud code insights
API endpoints. The implementation has been done under the consideration that in
newer versions no dedicated ALM support for bitbucket cloud exists, thus this
implementation is minimal invasive.
One thing to note here:
* For local testing the link on CloudCreateReportRequest has to be set manually to a non localhost URL since
bitbuckets API doesn't support it.

Adds support for Bitbucket Cloud Code Insights

---

build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/DeleteBindingAction.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/GetBindingAction.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/ListAction.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/ListDefinitionsAction.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/ProjectWsAction.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/SetBindingAction.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/gitlab/CreateGitlabAction.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/gitlab/UpdateGitlabAction.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/DeleteBindingActionTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/GetBindingActionTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/ListActionTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/ListDefinitionsActionTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/SetBindingActionTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/gitlab/CreateGitlabActionTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/gitlab/UpdateGitlabActionTest.java

Sonarqube 8.2 introduced a new `ProjectDto` with associated changes in `ProjectAlmSettingsDao` to require this new class in various methods, as well as changes in `ComponentFinder` to allow retrieval of instances of a project.
As this class and the associated methods did not exist in previous versions of Sonarqube, this change breaks backwards compatibility, so means the plugin will now only support Sonarqube 8.2.
Sonarqube 8.2 also provides the ability to set the optional URL parameter on a Gitlab project so that scans run outside of Gitlab CI operate properly, so the additional parameter is now included in the appopriate WebServices and the Gitlab decorator.

Add support for Sonarqube 8.2.0

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketCloudClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketServerClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/AnnotationUploadLimit.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketCloudClientUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketServerClientUnitTest.java

This commit fixes an issue with Bitbucket Cloud if more than 100 annotations
are present. Annotations will be chunked from now on on batches of 100 until
the total allowed of 1000 is reached.
For Bitbucket Server nothing changed.
Closes #209
Example error message:
```
sonarqube    | 2020.07.17 19:52:19 INFO  ce[AXNeVZecvjAJsjSGH1p9][c.g.m.s.p.c.p.b.c.BitbucketCloudClient] Create report on bitbucket cloud
sonarqube    | 2020.07.17 19:52:20 INFO  ce[AXNeVZecvjAJsjSGH1p9][c.g.m.s.p.c.p.b.c.BitbucketCloudClient] Creating annotations on bitbucket cloud
sonarqube    | 2020.07.17 19:52:21 INFO  ce[AXNeVZecvjAJsjSGH1p9][c.g.m.s.p.c.p.b.c.BitbucketCloudClient] Creating annotations on bitbucket cloud
sonarqube    | 2020.07.17 19:52:22 INFO …
```

Allows the bitbucket clients to have different upload limits

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProvider.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProviderTest.java

We have a mono repo with multiple microservices in it.
If multiple microservices are modified at once then only the final sonarqube PR decoration appeared in the checks tab of Github. This change updates the name of the Status check to include the sonarqube project name so that multiple checks can be attached to the one pull request.
Tested and verified the functionality on Sonarqube 8.3

[GITHUB] Add support for multiple pull request decoration - mono repo support

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/gitlab/SetGitlabBindingAction.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/gitlab/SetGitlabBindingActionTest.java

Enables GitLab merge request to be decorated. This PR fixes issue #201 for SonarQube 8.2+.

Bugfix: #201 could not decorate gitlab merge request

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/markup/MarkdownFormatterFactory.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/markup/MarkdownFormatterFactoryTest.java

Escapes HTML tags in GitLab Merge Request decorations. This PR fixes issue #93. This PR depends on PR #214.

Bugfix: #93 html tags not escaped on gitlab pull request decoration

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetailsTest.java

I have noticed that the Code Smell group in the PR decoration uses the same icon as the Vulnerabilities group.
This PR fixes this minor bug. It also includes the updated tests.

fix code smell image path in the analysis summary

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/CodeInsightsAnnotation.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/cloud/CloudAnnotation.java

The message displayed in the annotation on the pull request is a URL which points to the issue in SonarQube. 
This is because the `summary` field of the annotation body is serialising `link`. See screenshot.
```
public class CloudAnnotation extends CodeInsightsAnnotation {
@JsonProperty("external_id")
private final String externalId;
@JsonProperty("summary")
private final String link;
@JsonProperty("annotation_type")
private final String annotationType;
```
Is this intentional? Would it not be better to serialise the message instead? Then the analysis message is visible directly in the PR.  
Furthermore, I can't see anywhere in the Bitbucket API where `message` is specified in annotation body.
```
public class CodeInsightsAnnotation {
@JsonProperty("line")
private final int line; …
```

Bitbucket Cloud PR Decoration - Annotation summary is displaying a URL instead of the user message

---

.gitignore
build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PostAnalysisIssueVisitor.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetailsTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PostAnalysisIssueVisitorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProviderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecoratorTest.java

The collection of `DefaultIssue` objects hold by the `PostAnalysisIssueVisitor` can take a significant amount of memory in the CE process heap, when there are numerous issues (a `DefaultIssue` alone can weigh several 10th of kilobytes). 
A small example in Eclipse MAT (and I've seen much worse):
This PR mostly fixes that. The logic is unchanged: there is still a list of issues to be processed at the end. But it contains lighter objects, with only the few members which would actually be used later to decorate pullrequests. On our production instances (1.3.2 plugin / SQ 7.9 LTS), a similar patch made a major difference on the CE processes memory footprint.
I've tried to write this patch to minimize impact/changes on the code. The `PostAnalysisIssueVisitor.LightIssue` class exposes a subset …

Reduce memory usage of the PostAnalysisIssueVisitor

---

.gitignore
build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityReportAnalysisComponentProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PostAnalysisIssueVisitor.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsServerPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/AzurePullRequestDetails.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/Comment.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/CommentPosition.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/CommentThread.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/CommentThreadContext.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/CommentThreadResponse.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/GitPullRequestStatus.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/GitStatusContext.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/IdentityRef.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/Link.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/ReferenceLinks.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/enums/CommentThreadStatus.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/enums/CommentType.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/enums/GitStatusState.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/model/mappers/GitStatusStateMapper.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/ScannerPullRequestPropertySensor.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityReportAnalysisComponentProviderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetailsTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PostAnalysisIssueVisitorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsServerPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/ScannerPullRequestPropertySensorTest.java

Implements #102
Add support for Azure DevOps PR Decoration
Notes:
The following should be set in the scanner properties:
sonar.pullrequest.vsts.instanceUrl=https://[organization].visualstudio.com/
sonar.pullrequest.vsts.project=[Project]
sonar.pullrequest.vsts.repository=[Repository]
Ensure that the following option is unchecked in the Azure DevOps Branch Policy configuration, otherwise an exception will be thrown:
"Reset status whenever there are new changes"

Sq 8 2+azure devops

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/server/ErrorResponse.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketExceptionTest.java

There are situations where Bitbucket server is returning an error during API calls, but has no messages specified in the response body, so is causing a `NullPointerException` to be thrown by the plugin whilst attempting to provide details on the error. Specifically checking for the messages not being present allows for the underlying HTTP status code to be returned in the exception details so the user can get a better understanding of what the issue is.

#243: Handle no messages in error response from Bitbucket

---

build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/server/CommunityBranchSupportDelegate.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/CommunityComponentKey.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/ListDefinitionsAction.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/github/CreateGithubAction.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/github/GithubRequestParameterManager.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/github/UpdateGithubAction.java
src/test/java/com/github/mc1arke/sonarqube/plugin/classloader/ClassReferenceElevatedClassLoaderFactoryTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/classloader/ReflectiveElevatedClassLoaderFactoryTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/CommunityBranchSupportDelegateTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/ListDefinitionsActionTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/github/CreateGithubActionTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/github/UpdateGithubActionTest.java

Sonarqube 8.5.0 removed the `BranchSupport.Branch` class which breaks backwards-compatibility with previous Sonarqube versions, and requires updating how the ComponentKey is checked and generated during the creation of the analysis report. This version of Sonarqube also moves the bundled plugins into their own directory, so the build classpath has been updated to exclude those plugins from being able to be part of the compilation path, and updates the class-loading unit tests to reference a plugin class and file path that is still available in the newer Sonarqube version.

Add support for Sonarqube 8.5.0

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketCloudClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketServerClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/AnnotationUploadLimit.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketCloudClientUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketServerClientUnitTest.java

This commit fixes an issue with Bitbucket Cloud if more than 100 annotations
are present. Annotations will be chunked from now on on batches of 100 until
the total allowed of 1000 is reached.
For Bitbucket Server nothing changed.
Closes #209

#209: Allow the Bitbucket clients to have different upload limits

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/CodeInsightsAnnotation.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/model/cloud/CloudAnnotation.java

In #237 the property names of the annotation model were changed to fix a bug with how code annotations are reported to Bitbucket Cloud. This PR however did not take into consideration that the previous naming was actually correct and required for Bitbucket Server. With this change Bitbucket Cloud will continue to receive the message as `summary` ([API docs](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/commit/%7Bcommit%7D/reports/%7BreportId%7D/annotations)), while Bitbucket Server receives the message as `message` again ([API docs](https://docs.atlassian.com/bitbucket-server/rest/7.7.0/bitbucket-code-insights-rest.html#idp12)). This closes #265.
I moved the `@JsonProperty` annotations to the getters so that they support …

Fix Bitbucket Server PR decoration

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecorator.java

Issues with type SECURITY_HOTSPOT were reported to BitBucket even when they were marked as Resolved in SonarQube.

Remove resolved SECURITY_HOTSPOTS from BitBucket annotations

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecorator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabServerPullRequestDecoratorTest.java

Reworked version of #157 (and #145). Third time's the charm, right? 🤞
The coverage send back via the GitLab API should be the total coverage
of the project, not the coverage of the new code in the PR. The GitLab
docs explicitly mention this: 
https://docs.gitlab.com/ee/api/commits.html#post-the-build-status-to-a-commit
The coverage reported by decorating the PR via a comment is not affected;
this still shows both the total and new coverage.
Note that there is an open GitLab issue for natively displaying new coverage
for just the diff of a PR (https://gitlab.com/gitlab-org/gitlab/-/issues/20895),
but this is not yet implemented.
In addition, reporting coverage back is optional. So if there is no coverage
information, we do not report it back.

Send total coverage back to GitLab instead of new coverage

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/AddComment.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GetPullRequest.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/SetGithubBindingAction.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProviderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/SetGithubBindingActionTest.java

This pull request implement the support of the "Enable analysis summary under the GitHub Conversation tab" parameter for GitHub PullRequest analysis.
Screenshot of pull request comment submitted by SonarQube :

Add support of summaryComment on GitHub

---

src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchAgent.java
src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchAgentTest.java

The default distribution of Sonarqube only allows a single instance of each ALM to be configured, which prevents using ALM decoration where 2 different repositories require different API keys in a single ALM. To allow multiple configurations to be defined per ALM, the `MultipleAlmFeatureProvider` is being intercepted by the agent for the Web component and the `enabled` method being replace to always return `true`, thereby removing the limit on ALMs in the front-end.

#366: Allow defining multiple configurations per ALM

---

build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketClientFactory.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketCloudClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketServerClient.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketCloudClientUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketServerClientUnitTest.java

When Bitbucket Pull Request decoration fails due to an error from Bitbucket, diagnosing the cause of the failure can be challenging due to the lack of logs. This change therefore adds an interceptor to the HTTP client used in Bitbucket decoration which logs HTTP request headers and body content to the Sonarqube logs at debug level.

#334: Add ability to collect Bitbucket HTTP debug logs

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketClientFactory.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/client/BitbucketClientFactoryUnitTest.java

The BitBucket cloud decorator was attempting to perform an OAuth negotiation during construction in unit tests, so was dependent on the availability of BitBucket for the tests to pass. The `BitbucketClientFactory` has been altered to take an OkHttp Client Builder Supplier as an argument, with the tests injecting a mock client builder so no Http calls are performed during the BitBucket decorator tests.

Prevent BitBucket unit tests initiating real HTTP calls

---

src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchAgent.java
src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityPlatformEditionProvider.java
src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchAgentTest.java

The New Code Period webservices contain logic that specifically sets the target branch UUID to the main branch of the project if the Community version of Sonarqube is being used, thereby overriding the branch name that's been saved in the new code period's value.
The existing Java Agent functionality has been extended to alter the constructors of the relevant New Code services so they override the bundled Edition Provider that specifies the current platform edition as being Community edition, and instead injects a provider that overrides the current distribution as Developer edition, thereby causing the webservice logic to skip applying defaults for branch values.

#272: Ensure New Code Period settings are persisted

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsServerPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecorator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetailsTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsServerPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecoratorTest.java

Sonarqube uses a different URL format for issues compared to Security Hotspots, but the plugin was using the same format for both during Pull Request decoration, so linking to invalid URLS for hotspots. The URL generation has therefore been altered to take the issue type into account when generating a link to each issue.

#276: Use correct link on Pull Request annotations for Hostspots

---

build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecorator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetailsTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecoratorIntegrationTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecoratorTest.java

The Gitlab decorator treated any comment posted by the current Gitlab user as having been submitted for the current Sonarqube project, and therefore resolved any threads that no active issue could be found for in the current analysis. This prevented the decorator being used for a mono-repo as issues from decorations for other projects based in the repo would be resolved as subsequent projects completed their analysis.
The decorator has been changed to include the project ID in the details extracted from the existing comments, and to filter out any comments with project keys that do not match the project key the analysis is being performed for, before closing any remaining discussions, so that comments from other Sonarqube projects are not prematurely closed.

#377 Allow decorating Gitlab Mono Repository Merge Requests

---

.github/dependabot.yml

Adds dependabot configuration for Gradle and Github actions to ensure these dependencies are being kept up-to-date.

Add basic Dependabot configuration

---

src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPluginBootstrapTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPluginTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/classloader/ReflectiveElevatedClassLoaderFactoryTest.java

Some tests currently use Mockito to create mock classloaders, which do not then call `super` properly so cause classes to be defined with no module and cause subsequent JVM crashes when these classes are used later in the testsuite on newer Mockito versions.
An internal Mockito class has also been incorrectly referenced in a test in place of a Sonarqube class with a similar name, and a spy setup incorrectly around a mock, both of which fail in the latest Mockito version. These have both been updated to work correctly regardless by referencing the correct Sonarqube class and using the mock directly, rather than attempting to spy an already mocked instance.

Fix bad usages of Mockito classes

---

build.gradle

Junit 4 is used directly in tests but is only transitively inherited from other dependencies, which causes an issue if any of those dependencies require updating and drop their JUnit 4 dependency. To overcome this, JUnit 4 is being added as a direct dependency to the project's test scope.

Add direct dependency on JUnit 4

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/Actor.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/Comments.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GetPullRequest.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlGithubClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/MinimizeComment.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/PageInfo.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/Viewer.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/model/CommentClassifiers.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlGithubClientTest.java

When multiple Sonarqube analyses are performed against a Github Pull Request, each analysis generates a summary comment but none of the previous comments are cleaned-up on any subsequent analysis. To prevent a Pull Request becoming cluttered with summary comments, a search is being performed for all comments made by the current user, and all those comments are being minimized to prevent them being shown in-full on the Github user interface. As code level annotations are not treated as comments, this change has no impact on the individual findings within a Pull Request, only on the post-scan summary comment.

Hide outdated summary comments on GitHub

---

.env
gradle.properties
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/Actor.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/Comments.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GetPullRequest.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/MinimizeComment.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/PageInfo.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/Viewer.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/model/CommentClassifiers.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/v4/GraphqlCheckRunProviderTest.java

When multiple Sonarqube analyses are performed against a Github Pull Request, each analysis generates a summary comment but none of the previous comments are cleaned-up on any subsequent analysis. To prevent a Pull Request becoming cluttered with summary comments, a search is being performed for all comments made by the current user, and all those comments are being minimized to prevent them being shown in-full on the Github user interface. As code level annotations are not treated as comments, this change has no impact on the individual findings within a Pull Request, only on the post-scan summary comment.

GitHub summary comment backport

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/azuredevops/model/enums/CommentThreadStatus.java

Apply appropriate casing to CommentThreadStatus property names

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/azuredevops/AzureDevopsRestClient.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsPullRequestDecoratorTest.java

Azure DevOps on-premise responds with an error if the `-preview` is not appended to the version number during the request to submit the pipeline status during Pull Request decoration. As the use of a preview version for this call does not seem to adversely affect invocation of this endpoint on Azure DevOps Cloud, the `-preview` flag has been unconditionally added to the status update, although it has not been added to any other invocations since they do not encounter the same error.

#442: Pass preview flag on Azure Devops status requests

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/azuredevops/AzureDevopsRestClient.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/azuredevops/AzureDevopsRestClientTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsPullRequestDecoratorTest.java

Azure DevOps does not correctly resolve URLs that contains spaces encoded as a `+`. To allow projects containg spaces to be decorated, the `+` from an the encoded names is being replaced with a `%20` since Azure Devops resolves spaces encoded this way properly.

#461: Correctly encode spaces in Azure DevOps URLs

---

build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/azuredevops/DefaultAzureDevopsClientFactory.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/DefaultBitbucketClientFactory.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/DefaultGithubClientFactory.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/gitlab/DefaultGitlabClientFactory.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/SetBindingAction.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/DefaultBitbucketClientFactoryUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/github/DefaultGithubClientFactoryTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlGithubClientTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PullRequestPostAnalysisTaskTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecoratorIntegrationTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/action/SetBindingActionTest.java

Sonarqube 9.1 encrypts the sensitive fields for DevOps decorators, such as private keys and personal access tokens. To allow the decorators to access these properties, the relevant methods now require encryption details to be provided, so the encryption handlers are now being loaded from the internal Sonarqube settings and passed to the appropriate target methods.
A change is also required in `SetBindingsAction` to pass additional fields for recording on the audit log when settings are saved. No additional settings are being added for the auditing as community edition does not provide a user interface for accessing audit logs, and uses a default cleaner task for purging logs after 30 days.

#454: Add support for Sonarqube 9.1

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketServerClient.java

One of the method of BitbucketServerClient is not using correct url to call bitbucket client what results in error in UI

Add missing base url while using bitbucket client

---

src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPlugin.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/BranchAutoConfigurer.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/BranchConfigurationFactory.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfigurationLoader.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/autoconfiguration/AzureDevopsAutoConfigurer.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/autoconfiguration/BitbucketPipelinesAutoConfigurer.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/autoconfiguration/CirrusCiAutoConfigurer.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/autoconfiguration/CodeMagicAutoConfigurer.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/autoconfiguration/GithubActionsAutoConfigurer.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/autoconfiguration/GitlabCiAutoConfigurer.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/autoconfiguration/JenkinsAutoConfigurer.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/BranchConfigurationFactoryTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfigurationLoaderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/autoconfiguration/AzureDevopsAutoConfigurerTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/autoconfiguration/BitbucketPipelinesAutoConfigurerTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/autoconfiguration/CirrusCiAutoConfigurerTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/autoconfiguration/CodeMagicAutoConfigurerTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/autoconfiguration/GithubActionsAutoConfigurerTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/autoconfiguration/GitlabCiAutoConfigurerTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/autoconfiguration/JenkinsAutoConfigurerTest.java

The plugin previously only provided support for auto-detecting and configuring the scanner properties for a Pull Request in Azure Devops and a Merge Request or Branch in Gitlab CI. The Sonarqube documentation also stated that Bitbucket Pipelines, Github Actions, CodeMagic, Jenkins Branch API, and Cirrus CI could also be used to auto-discover Pull Request or Branch information although the plugin did not provide these.
This change adds support for detecting these additional CIs based on the various environment variables they provide, and to auto-configure Pull Request or Branch parameters in the scanner when a suitable build job is detected.
Includes the general clean-up of the creation of Branch and Pull Request configuration to force fail-fast behaviour where target branches are not …

#523: Add auto-detection for all CIs in Sonarqube commercial editions

---

src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPlugin.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketCloudClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketServerClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/DefaultBitbucketClientFactory.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/HttpClientBuilderFactory.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/model/ReportStatus.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/model/server/BitbucketServerConfiguration.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityReportAnalysisComponentProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PostAnalysisIssueVisitor.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/validator/BitbucketValidator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPluginTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketCloudClientUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketServerClientUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/DefaultBitbucketClientFactoryUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/HttpClientBuilderFactoryTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetailsTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PostAnalysisIssueVisitorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/validator/BitbucketValidatorTest.java

The Bitbucket clients require different properties to be used from the
relevant configuration DTOs depending on whether Bitbucket cloud or
server are being used, with the management of the property retrieval
being delegated to the relevant client implementation. However, this
requires each client to reference DTO classes from Sonarqube core, where
the clients should really only interact with their own models.
As the work on retrieving the relevant details has already been
performed in the `DefaultBitbucketClientFactory`, the logic for
performing the retrieval has been removed from each client
implementations, and the calculated values are passed into the
constructor for each client instead. This does make each client instance
constrained to a single  repository, but given the way the …

Refactor Bitbucket operations to prevent leaking scope

---

src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPlugin.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/DefaultGithubClientFactory.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/GithubClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/RepositoryAuthenticationToken.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/model/Annotation.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/model/CheckRunDetails.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v3/DefaultUrlConnectionProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v3/RestApplicationAuthenticationProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v3/model/Owner.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/DefaultGraphqlProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GetRepository.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlGithubClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityReportAnalysisComponentProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/GithubPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/markup/FormatterFactory.java
src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPluginTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/github/DefaultGithubClientFactoryTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v3/RestApplicationAuthenticationProviderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlGithubClientTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityReportAnalysisComponentProviderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/GithubPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecoratorIntegrationTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecoratorTest.java

The GithubClient interface exposes a method that takes various Sonarqube
core classes and plugin constructed data as arguments and returns a
`DecorationResult`, all of which are items that the upstream decorator
should be aware of, but not the client responsible for communicating
with Github. Similarly, the `GraphqlGithubClient` had locally
constructed a `MarkdownFormatterFactory`, `DefaultGraphqlProvider`, and
`Clock` as well as requiring a Sonarqube `Server` instance for
instantiation, with the local construction requiring a second
constructor to be included purely for testing, and the `Server` instance
requiring the client have knowledge of Sonarqube's structure rather than
being passed a client configuration that had no external dependencies in
it.
This change alters the GithubClient …

Refactor Github operations to prevent leaking scope

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/markup/MarkdownFormatterFactory.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/markup/MarkdownFormatterFactoryTest.java

The text renderer for the `MarkdownFormatterFactory` had been performing
a `trim` on any inputs, which caused the single whitespace entries being
added as spacers after some inline images to be removed. As the
structure of the document should be presumed to match what the
generating component requires, it's unnecessary for the renderer to
attempt to alter this structure whilst rendering to a relevant document
format. Instead, any constraints on formatting should be left to the
system rendering the generated output.

#421: Don't trim whitespace during Markdown rendering

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityReportAnalysisComponentProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetails.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/DiscussionAwarePullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PostAnalysisIssueVisitor.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PullRequestPostAnalysisTask.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/GithubPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/report/AnalysisIssueSummary.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/report/AnalysisSummary.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/report/ReportGenerator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlGithubClientTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityReportAnalysisComponentProviderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetailsTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PostAnalysisIssueVisitorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PullRequestPostAnalysisTaskTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/GithubPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecoratorIntegrationTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/report/AnalysisIssueSummaryTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/report/AnalysisSummaryTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/report/ReportGeneratorTest.java

The access to metrics from a Pull Request analysis is exposed through an
`AnalysisDetails` instance, which also provides the ability to extract a
formatted report. As a number of the metrics used in the summary report
need to be retrieved through various additional DAOs, and as the
resolution of URLs for links and images requiring access to core
Sonarqube configuration, `AnalysisDetails` holds references to a high
number of classes from Sonarqube's core. Some of those core Sonarqube
classes are also referenced directly in some decorators which don't make
use of the summary report but need equivalent metrics to those shown in
the summary which means some searching logic is duplicated across the
plugin.
This change pulls the report generation into a `ReportGenerator` class,
with the report …

Move report generation out of AnalysisDetails

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketCloudClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketServerClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecorator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketCloudClientUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketServerClientUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecoratorTest.java

The key for the Code Insights report uses a static value which results
in any report submitted by Sonarqube overwriting any existing report,
even where reports are submitted from different projects, such as would
happen in a mono-report setup. The report key is therefore being changed
to use the project key, so that repeated scans from a single project
continue to overwrite each other, whilst scans against the same
repository from different projects will allow new reports to be
submitted without altering existing reports.

Allow mono-repo decoration for Bitbucket

---

build.gradle

iirc default charset on Windows is windows-1252 which causes unit tests to fail https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/569#issuecomment-1097698884 we can work around this by specifying utf8 in the gradle build file.

Fix unit tests on Windows.

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/gitlab/model/MergeRequest.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecorator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecoratorIntegrationTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecoratorTest.java

Fix has been done using target_project_id instead of source_project_id.

#554 Decoration issue fails due invalid project id when branch is in fork

---

src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/azuredevops/AzureDevopsRestClientTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/gitlab/GitlabRestClientTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecoratorIntegrationTest.java

The wiremock based tests currently fail if another service is running on
on port 8080, and other tests fail with newer dependencies due to
changes in recursive comparisons. The wiremock tests are being altered
to use a random port for runs to prevent port conflict, and the tests
comparing HTTP entities are being altered to extract the InputStream for
comparing the contents from.

Improve test stability

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/DefaultBitbucketClientFactory.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/model/BitbucketConfiguration.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/model/server/BitbucketServerConfiguration.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecorator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketCloudClientUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketServerClientUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecoratorTest.java

With the Sonar 9.4 support the project key and repository slug for Bitbucket repositories got swapped, causing the plugin not being able to find the repository to send the PR report to.
The available ObjectMapper modules also had to be registered in order write the report timestamp to JSON.

Fix Bitbucket PR reports

---

README.md

This PR adds instructions for the plugin installation for [Sonarqube official Helm Chart](https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube) users.
The instruction also covers problems with incorrect copy paths, which are occurring only when persistence is enabled in installation.
The plugin works well with a kubernetes environment, however, this use case is not covered in installation instructions, which are not trivial.
_Related to #609_

Add instructions for official SonarQube Helm Chart

---

README.md

Re-formats the README to limit the line lengths to improve editing and
readability of the raw format, and fixes some references to paths and
configuration that has changed in recent versions of Sonarqube but is
no longer accurate in the README.

Cleanup README contents

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsPullRequestDecorator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsPullRequestDecoratorTest.java

When creating the link from Sonarqube to an Azure Devops Pull Request,
the URL of the owning repository is used as a base for the URL. If the
Azure DevOps API returns a URL containing user authentication details
then this is included in the resulting link, even though the details
may not be valid for a front-end user. The authentication detail is
therefore being stripped from the URL before the Pull Request URL is
generated.

#601 Strip user info from Azure DevOps repository link

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v3/RestApplicationAuthenticationProvider.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v3/RestApplicationAuthenticationProviderTest.java

The current implementation of the RestApplicationAuthenticationProvider contains an instance-level Object Mapper but doesn't use it instead constructing a new Object Mapper on each invocation and eagerly loads all pages of App Installations even though the first page may contain a token with access to the required repository. The implementation has therefore been altered to use the constructed object mapper for all operations and to work through the full contents of a page of AppInstallations before moving on to the next page of installations.

Clean-up retrieval of Github authentication tokens

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml
build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchAgent.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfigurationLoader.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/CommunityBranchFeatureExtension.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/CommunityBranchSupportDelegate.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/MonoRepoFeature.java
src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchAgentTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfigurationLoaderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/CommunityBranchFeatureExtensionTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/CommunityBranchSupportDelegateTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/MonoRepoFeatureTest.java

Sonarqube 10 has removed legacy support for modules as well as removing deprecated properties historically used for specifying branch targets. Additionally, the interface for managing Sonarqube features has had a method renamed, which makes the new version of Sonarqube binary incompatible with the plugin. The references to Sonarqube's removed code have been removed from the plugin, and the implementations of the interface and Java agent that dynamically updates Sonarqube code that also implements the interface have been updated to use the new method name.

#753: Add support for Sonarqube 10.0

---

.env
Dockerfile

Sonarqube 10.1 includes classes compiled with a Java 17 target, so the plugin fails to compile in the container build that uses Java 11. The build container is therefore being bumped to Java 17, and the environment file configured to pin to Sonarqube 10.1 to allow repeated builds.

#782: Fix container build for Sonarqube 10.1

---

build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchAgent.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/azuredevops/AzureDevopsRestClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketCloudClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketServerClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/DefaultBitbucketClientFactory.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlGithubClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/gitlab/GitlabRestClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PullRequestPostAnalysisTask.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityBranchConfigurationLoader.java

The Sonar logger has been deprecated in favour of SLF4J's Logger and LoggerFactory, so the references have been replaced throughout the plugin, and log lines updated to use formats and conditional execution. Includes fixes to make Pi Test work in the Gradle build.

Remove references to deprecated Sonar logger

---

.env
build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityBranchLoaderDelegate.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/CommunityBranchSupportDelegate.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/binding/action/ProjectWsAction.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/pullrequest/action/DeleteAction.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/pullrequest/action/ListAction.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityBranchLoaderDelegateTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/AnalysisDetailsTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/CommunityBranchSupportDelegateTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/binding/action/DeleteBindingActionTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/binding/action/ValidateBindingActionTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/pullrequest/action/DeleteActionTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/pullrequest/action/ListActionTest.java

The `checkProjectPermission` on Sonarqube's UserSession has been replaced with `hasEntityPermission`, and the `mainBranchProjectUuid` has been dropped from ComponentDTO, which has required a fix to set the right UUID as the project UUID for the branch. Additionally, the `MoreCollectors` map/identity collectors have been dropped from Sonarqube core, so their references have been replaced with equivalent `toMap` collectors from the JRE.

#801: Add support for Sonarqube 10.2

---

LICENSE

The project contains LGPL headings in all the source files and is intended to be licensed as an LGPL project, but contains a GPL license file in the project root. As contributors have been committing with LGPL headers this switch is being made without any wider changes across the project.

Fix reference license in project root

---

.github/workflows/build.yml

Since the Gradle upgrade and the associated Sonarqube plugin upgrade, Sonarcloud has been reporting no coverage on the project's main branch. This is due to the Sonarqube plugin no longer executing the test task so have no coverage report available. The relevant pipeline steps are being altered to run the `test` task before the Sonarqube task, and have switched to the new `sonar` name for the task, as well as removing the compile task dependency since this is implicit from the test task and matches the future state of Sonarqube's Gradle plugin.

Ensure correct coverage is reported to Sonarcloud

---

src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/BranchConfigurationFactory.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/pullrequest/action/ListAction.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/BranchConfigurationFactoryTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/pullrequest/action/ListActionTest.java

The scanner currently skips validation of a target branch if a Pull Request is used to create a new project, so the resulting project fails to load in front-end due to the Pull Request API treating the data on that pull request as invalid. This is being overcome by validating that a target branch exists for all Pull Request submissions and rejecting the scan submission if the target branch is not found in Sonarqube.
Additionally, there's a delay between a Pull Request being recorded in the database by the server component as a result of the call from the scanner, and the Compute Engine recording the Pull Request details (source, target, title etc.) against the branch. During this time the Pull Request treats that Pull Request as invalid and throws an error, meaning the project cannot be …

#738: Prevent missing pull request data from causing API errors

---

build.gradle

When the release plugin was upgraded, the configuration was not altered to set a pre-release task needing executed, so no plugin JAR was being created as part of the release step. The `assemble` task is now being set to ensure the JAR exists in the relevant output directory for dependent steps to pick up.

Fix release task not creating any artefacts

---

.env
build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/server/CommunityBranchSupportDelegate.java

The constants in `CeTaskCharacteristicsDto` have been moved into a new class `CeTaskCharacteristics`, so the references in the plugin have been updated.

#829: Add support for Sonarqube 10.3

---

.env
build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v3/RestApplicationAuthenticationProvider.java
src/test/java/com/github/mc1arke/sonarqube/plugin/classloader/ClassReferenceElevatedClassLoaderFactoryTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/classloader/ReflectiveElevatedClassLoaderFactoryTest.java

When installed into SonarQube 10.4, community-branch-plugin fails with
```
Caused by: java.lang.NoSuchMethodError: 'io.jsonwebtoken.JwtBuilder io.jsonwebtoken.JwtBuilder.setExpiration(java.util.Date)'
at com.github.mc1arke.sonarqube.plugin.almclient.github.v3.RestApplicationAuthenticationProvider.getInstallationToken(RestApplicationAuthenticationProvider.java:81)
at com.github.mc1arke.sonarqube.plugin.almclient.github.DefaultGithubClientFactory.createClient(DefaultGithubClientFactory.java:56)
at com.github.mc1arke.sonarqube.plugin.server.pullrequest.validator.GithubValidator.validate(GithubValidator.java:43)
at com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.binding.action.ValidateBindingAction.validateProject(ValidateBindingAction.java:73)
at …
```

SonarQube 10.4 compatibility fixes

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlGithubClient.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlGithubClientTest.java

It seems like the https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/884 change has affected minimization of comments for SonarQube instances that run on Linux or macOS.
The root cause is that `MarkdownFormatterFactory` uses `System.lineSeparator()` as the end-of-line character for annotation comments. `GraphqlGithubClient.postSummaryComment()`, however, uses hardcoded `\r\n` as end-of-line character, so it isn't able to match legitimate comments if SonarQube is not running on Windows.
This change updates `GraphqlGithubClient` to also use system end-of-line char.
(It also moves `String.format` call out of the comment iteration logic to avoid making multiple identical calls).

Fix detection of previous PR annotation comments

---

build.gradle

As far as I know this should be enough to produce a binary compatible plugin for SonarQube 10.5. See also https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/900#issuecomment-2075860129.

SonarQube 10.5 compatibility

---

.env
build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityProjectBranchesLoader.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/CommunityRepositoryBranchesLoaderTest.java

`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'java.net.FactoryURLClassLoader@6441c486-com.github.mc1arke.sonarqube.plugin.scanner.CommunityProjectBranchesLoader': Resolution of declared constructors on bean Class [com.github.mc1arke.sonarqube.plugin.scanner.CommunityProjectBranchesLoader] from ClassLoader [java.net.FactoryURLClassLoader@6441c486] failed; nested exception is java.lang.NoClassDefFoundError: org/sonar/scanner/bootstrap/ScannerWsClient`

Update to SonarQube 10.6

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/report/AnalysisSummary.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/report/AnalysisSummaryTest.java

Where Sonarqube does not have duplication information recorded on a branch, such as there being no code to analyse, the duplication information may be null. THe plugin is being altered to show this as a `0` rather than throwing an exception when trying to format the missing value.

#715: Handle duplication information not being present

---

src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/pullrequest/action/ListAction.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/pullrequest/action/ListActionTest.java

The component ID was being used to create a map of analysis dates to items, but the Pull Request's component ID did not map into this item, so the Pull Request web service was always returning the analysis date as empty. The service has been altered to use the root component ID as was used in the search to ensure the IDs align.

#940: Use correct component IDs when extracting analysis date

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityReportAnalysisComponentProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PullRequestFixedIssuesIssueVisitor.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/CommunityReportAnalysisComponentProviderTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/PullRequestFixedIssuesIssueVisitorTest.java

Sonarqube currently reports a fixed issues metric for pull requests, but the plugin isn't providing the data to allow that value to be calculated. To resolve this an additional IssueVisitor has been introduced that compares the issues from the target branch with the findings on the source branch and finds any target code blocks that no longer exists - implying the issue line has been removed - or any code that still exists but is now reporting the issue as fixed, and reports them to the PullRequestFixedIssuesRepository which is used within Sonarqube to gather the count of issues fixed in the current analysis.

#945: Gather statistics for issues fixed in a pull request

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/DefaultGraphqlProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlGithubClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlProvider.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/InputObject.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/github/v4/GraphqlGithubClientTest.java

The Github Cloud API now returns an error about the input message being malformed, seemingly due to a change in how new lines in messages are being handled. As the use of blockquotes around multi-line messages appears to continue to work, the analysis messages are being wrapped in blockquotes rather than double-quotes where they contain newline characters. This requires an interim measure of cloning the InputObject class from the nodes library to alter the String comparison and wrapping since the library is no longer maintained.

#959: Ensure multi-line string are enclosed in blockquotes

---

src/main/java/com/github/mc1arke/sonarqube/plugin/scanner/BranchConfigurationFactory.java
src/test/java/com/github/mc1arke/sonarqube/plugin/scanner/BranchConfigurationFactoryTest.java

The resolution of Pull Request details currently uses the project default branch when a pull request is analysed without specifying a target branch. However, when a target branch is specified, the plugin expects that branch to exist and throws an exception if the target branch is not found. To overcome this, the target branch is being resolved to the default branch where no target branch is specified or the requested target branch does not exist. As the API used to gather branch information does not return PULL_REQUEST details, the result of this searching is that a pull request will either target a branch from the main branch, or target the main branch, there is no further nesting or pull requests and branches.

#909: Use default branch as Pull Request base when target does not exist

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecorator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecoratorTest.java

The Bitbucket decoration is currently using the project key to create the analysis report key, but the Sonarqube documentation states this should be a static value across all projects. To ensure that the Bitbucket `Required report` configuration can be created as per the guidance in Sonarqube documentation, the static key is being used where the repository has not been set as a monorepo.

#934: Use static report key for non-monorepo Bitbucket decoration

---

Dockerfile
release.Dockerfile

The sonarqube images no longer create a sonarqube group for the sonarqube user to be placed into, instead they put the sonarqube user in the root group. To prevent the plugin builds failing when attempting to set the plugin ownership to a group that doesn't exist, the `chown` command is being altered to only set the user ownership, not the associated group.

#958: Remove group assignment during container build

---

src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/pullrequest/action/ListActionTest.java

The service code uses DateUtils to convert a long into a String format, which DateUtils converting the long to an instant, then an OffsetDateTime before passing this through a formatter, using the local timezone during the OffsetDateTime conversion.
As the test was using a pre-created String based on the UTC timezone, the test does not correctly compare the values when being executed in a different timezone. To overcome this, the test has been altered to use the same DateUtils methods to convert from the long to a String, thereby ensuring the same timezone handling is using in both test and live code.

#972: Ensure a consistent timezone is used in comparisons

---

README.md

Helm chart values `jvmOpts` and `jvmCeOpts` were deprecated in [v8.3.1](https://github.com/SonarSource/helm-chart-sonarqube/releases/tag/sonarqube-10.0.0-sonarqube-dce-10.0.0). See https://github.com/SonarSource/helm-chart-sonarqube/commit/d42cc00b879705972e75a059bb80c0fc602fb62b

docs: Update helm chart value examples

---

Dockerfile
release.Dockerfile

Not all the Sonarqube image variants contain a group named sonarqube, so the `chown` command fails as it's unable to find the target group. To overcome this the group is being set to `0` which should always exist as the root user's group.

#958: Set plugin group ID to root in container build

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/azuredevops/AzureDevopsClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/azuredevops/AzureDevopsRestClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/azuredevops/model/Comment.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/azuredevops/model/ConnectionData.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/gitlab/GitlabClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/gitlab/GitlabRestClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/DiscussionAwarePullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecorator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsPullRequestDecoratorIntegrationTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/azuredevops/AzureDevOpsPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecoratorIntegrationTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/gitlab/GitlabMergeRequestDecoratorTest.java

The plugin historically left old comments in place but resolved conversations where comments had become outdated or the underlying issue had been resolved. However, in Gitlab, the summary comments always remained visible even when resolved as they were the first comment in the thread so were not minimised by the Gitlab UI. For a merge request being scanned multiple times as issues are being fixed, other review comments responded to, and rebasing activities performed, this can lead to a number of summary comments being added where the last comment is typically only the one that developers are about.
As editing comments is not good practice since it's unclear what any resulting comments in the thread are referring to and Gitlab does not send emails to notify that comments have changed, the …

Remove old Gitlab and Azure Devops summary comments on new decoration

---

src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchAgent.java
src/main/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPluginBootstrap.java
src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchAgentTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/CommunityBranchPluginBootstrapTest.java

Users currently submit a number of reports for Sonarqube reporting that branch analysis is not available despite them having the plugin installed, which are typically triggered by the user not having set up the Java agent on one of the components correctly. This is compounded by the Sonarqube plugin screen showing the plugin as being installed in these scenarios even where the plugin's classes and configuration have not been fully loaded into Sonarqube. To overcome this, the plugin bootstrap class is now checking for the agent having made an alteration to one of the bootstrap methods as an indication that the agent has run successfully for both the Compute Engine and Web components, with the plugin failing to start if either component doesn't detect the agent modifications, and therefore …

Check agent is correctly installed during plugin startup

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/GithubPullRequestDecorator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/GithubPullRequestDecoratorTest.java

Fixes #415
Use a static check name instead, which makes it easier to apply global rulesets to repositories.

fix: Update GitHub PR check name

---

.env
build.gradle
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/GithubPullRequestDecorator.java
src/main/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/pullrequest/action/ListAction.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/github/GithubPullRequestDecoratorTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/server/pullrequest/ws/pullrequest/action/ListActionTest.java

The latest release for Sonarqube has removed the LiveMeasures concept, instead just using Measures, and has moved to a new versioning strategy for community edition. The plugin has therefore been update to the latest version number of Sonarqube and the appropriate DAO and DTO references updated.

#1011: Add support for Sonarqube 24.12

---

src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/report/ReportGenerator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/report/ReportGeneratorTest.java

Sonarqube has the concepts of Multi Quality Rule metrics for quality gates, which use different metric keys from those used in standard quality metrics. To ensure we don't cause errors when attempting to resolve these new rules, if the original search does not find a matching metric then the mapping between standard and MQR metrics is performed and, if a match is found, the mapped key used to retrieve a metric. If no mapping is found then the current quality gate condition is skipped during the decoration.

#1043: Handle Multi Quality Rule metrics during decoration

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/azuredevops/AzureDevopsRestClient.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/azuredevops/AzureDevopsRestClientTest.java

Microsoft IIS isn't handling requests from the plugin during Azure Devops decoration as expected, seemingly due to the HTTP verbs being sent in lower case. To match the HTTP request spec the verbs are being transformed to uppercase before sending.

#1065: Send HTTP verbs in uppercase

---

src/main/java/com/github/mc1arke/sonarqube/plugin/classloader/ProviderType.java

The class reference class loader strategy currently loads a class from Sonarqube core that will be removed in future versions of Sonarqube since the Profile import and export features this class is part of have been deprecated. The reference is being replaced a non-deprecated class from the same API component.

#1075: Switch classloader injection to reference a stable class

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketCloudClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketServerClient.java
src/main/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecorator.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketCloudClientUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketServerClientUnitTest.java
src/test/java/com/github/mc1arke/sonarqube/plugin/ce/pullrequest/bitbucket/BitbucketPullRequestDecoratorTest.java

When using a monorepo with a long project key, Bitbucket server reports an error for the report key being too long during decoration. As the report key is based on the project key which is typically derived from a project's group ID and artefact ID, this may end up being a long value with limited control over setting its length. To overcome this, when sending a report to Bitbucket server, the project key will be truncated where it's more than 50 characters, and prepended with `t-` to make it clear the value was truncated and try and prevent conflicts with any other projects.

#897: Truncate report keys when sending to Bitbucket server

---

build.gradle
sonarqube-webapp-addons/src/branches/components/branch-like/PRLink.tsx
sonarqube-webapp-addons/src/branches/components/pull-requests/MeasuresCardPanel.tsx
sonarqube-webapp-addons/src/branches/components/pull-requests/PullRequestMetaTopBar.tsx
sonarqube-webapp-addons/src/branches/components/pull-requests/SonarLintAd.tsx

Upgrades to Sonarqube 25.5 for both front-end and back-end, with the required front-end changes to be compatible with upstream modifications.

Upgrade to Sonarqube 25.5

---

.env
Dockerfile
build.gradle
sonarqube-webapp-addons/setup.sh
sonarqube-webapp-addons/src/branches/app/ProjectBranchesApp.tsx
sonarqube-webapp-addons/src/branches/app/components/BranchLikeRow.tsx
sonarqube-webapp-addons/src/branches/app/components/BranchLikeTable.tsx
sonarqube-webapp-addons/src/branches/app/components/BranchLikeTabs.tsx
sonarqube-webapp-addons/src/branches/app/components/BranchPurgeSetting.tsx
sonarqube-webapp-addons/src/branches/app/components/DeleteBranchModal.tsx
sonarqube-webapp-addons/src/branches/app/components/LifetimeInformation.tsx
sonarqube-webapp-addons/src/branches/app/components/LifetimeInformationRenderer.tsx
sonarqube-webapp-addons/src/branches/app/components/RenameBranchModal.tsx
sonarqube-webapp-addons/src/branches/app/components/SetAsMainBranchModal.tsx
sonarqube-webapp-addons/src/branches/app/routes.tsx
sonarqube-webapp-addons/src/branches/components/branch-like/CurrentBranchLikeMergeInformation.tsx
sonarqube-webapp-addons/src/branches/components/branch-like/Menu.tsx
sonarqube-webapp-addons/src/branches/components/branch-like/MenuItem.tsx
sonarqube-webapp-addons/src/branches/components/branch-like/MenuItemList.tsx
sonarqube-webapp-addons/src/branches/components/branch-like/PRLink.tsx
sonarqube-webapp-addons/src/branches/components/branch-list/BranchList.tsx
sonarqube-webapp-addons/src/branches/components/branch-list/BranchListRow.tsx
sonarqube-webapp-addons/src/branches/components/branch-list/BranchListSection.tsx
sonarqube-webapp-addons/src/branches/components/branch-list/BranchNewCodeDefinitionSettingModal.tsx
sonarqube-webapp-addons/src/branches/components/pull-requests/BranchQualityGateConditions.tsx
sonarqube-webapp-addons/src/branches/components/pull-requests/MeasuresCardPanel.tsx
sonarqube-webapp-addons/src/branches/components/pull-requests/PullRequestMetaTopBar.tsx
sonarqube-webapp-addons/src/branches/components/pull-requests/PullRequestOverview.tsx
sonarqube-webapp-addons/src/branches/components/pull-requests/SonarLintAd.tsx

Updates the build process to reflect Sonarqube having renamed the addons directory to sq-server-addons, as well as changing front-end imports to match restructuring with Sonarqube.

Upgrade to Sonarqube 25.6

---

.env
build.gradle
gradle.properties
sonarqube-webapp-addons/src/branches/app/components/BranchLikeRow.tsx
sonarqube-webapp-addons/src/branches/app/components/BranchLikeTabs.tsx
sonarqube-webapp-addons/src/branches/app/components/BranchPurgeSetting.tsx
sonarqube-webapp-addons/src/branches/app/components/DeleteBranchModal.tsx
sonarqube-webapp-addons/src/branches/components/branch-like/Menu.tsx
sonarqube-webapp-addons/src/branches/components/branch-like/MenuItem.tsx
sonarqube-webapp-addons/src/branches/components/branch-like/PRLink.tsx
sonarqube-webapp-addons/src/branches/components/branch-list/BranchList.tsx
sonarqube-webapp-addons/src/branches/components/branch-list/BranchListRow.tsx
sonarqube-webapp-addons/src/branches/components/pull-requests/BranchQualityGateConditions.tsx
sonarqube-webapp-addons/src/branches/components/pull-requests/MeasuresCardPanel.tsx
sonarqube-webapp-addons/src/branches/components/pull-requests/PullRequestMetaTopBar.tsx
sonarqube-webapp-addons/src/branches/components/pull-requests/PullRequestOverview.tsx

Upgrades to Sonarqube 25.7 for both front-end and back-end. As the front-end repository does not contain a tag aligned to the 25.7 release, the last commit from the day of the current front-end release has been used for the webapp submodule.

Upgrade to Sonarqube 25.7

---

.env
build.gradle
gradle.properties

Updates to the 25.8 backend and front-end, with no additional changes required for plugin compatibility.

Upgrade to Sonarqube 25.8

---

src/main/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketServerClient.java
src/test/java/com/github/mc1arke/sonarqube/plugin/almclient/bitbucket/BitbucketServerClientUnitTest.java

Bitbucket server performs an XSRF check that requires the content-type is either complex (e.g. application/json) or that a special request header is added that indicates the request has been sent from a trusted source. As no content-type is set on GET or DELETE requests, the Atlassian XSRF header is being set on the request to indicate the request has come from a trusted source rather than being a cross-site request from an authenticated front-end.

#249: Add Atlassian XSRF protection to Bitbucket Server request
